FROM eclipse-temurin:19-jre-alpine as build

ENV ACTIVEMQ_VERSION 5.16.5
ENV ACTIVEMQ apache-activemq-$ACTIVEMQ_VERSION
ENV ACTIVEMQ_TCP=61616 ACTIVEMQ_AMQP=5672 ACTIVEMQ_STOMP=61613 ACTIVEMQ_MQTT=1883 ACTIVEMQ_WS=61614 ACTIVEMQ_UI=8161
ENV SHA512_VAL=d14e773f8e426c2c7b870637584db57660ad66449052725bfd27542f7a8acc235e3fc28a54dbdbe162c68da2685c4f9d42433e1a155cab4caa7646dde061a3d3

ENV USER_ID=65535
ENV GROUP_ID=65535
ENV USER_NAME=activemq
ENV GROUP_NAME=activemq

RUN apk add curl
RUN curl "https://archive.apache.org/dist/activemq/$ACTIVEMQ_VERSION/$ACTIVEMQ-bin.tar.gz" -o $ACTIVEMQ-bin.tar.gz

# Validate checksum
RUN if [ "$SHA512_VAL" != "$(sha512sum $ACTIVEMQ-bin.tar.gz | awk '{print($1)}')" ];\
    then \
        echo "sha512 values doesn't match! exiting."  && \
        exit 1; \
    fi;


RUN tar -xzf $ACTIVEMQ-bin.tar.gz -C  /opt && \
    addgroup -g $GROUP_ID $GROUP_NAME && \
    adduser --shell /sbin/nologin --disabled-password \
    --no-create-home --uid $USER_ID --ingroup $GROUP_NAME $USER_NAME && \
    chown -R $USER_NAME:$GROUP_NAME /opt/$ACTIVEMQ && \
    sed -i 's/127.0.0.1/0.0.0.0/g' /opt/$ACTIVEMQ/conf/jetty.xml

USER activemq

WORKDIR /opt/$ACTIVEMQ
EXPOSE $ACTIVEMQ_TCP $ACTIVEMQ_AMQP $ACTIVEMQ_STOMP $ACTIVEMQ_MQTT $ACTIVEMQ_WS $ACTIVEMQ_UI

CMD ["/bin/sh", "-c", "./bin/activemq console"]
